import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/base/Navbar";
import Footer from "@/components/base/Footer";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "PaperTheory",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}
      >
        {/* Site-wide Background */}
        <div className="fixed inset-0 w-full h-full pointer-events-none z-0">
          <img
            src="/bg.svg"
            alt="background"
            className="absolute inset-0 w-full h-full opacity-10 object-cover"
          />
        </div>

        <div className="relative z-10">
          <Navbar />
          {children}
          <Footer />
          
          {/* Floating GENZ Button */}
          <Link href="/genz" className="fixed bottom-6 left-1/2 transform -translate-x-1/2 bg-white text-black px-8 py-3 rounded-full shadow-2xl hover:bg-black hover:text-white border-2 border-black transition-all duration-300 z-50 group overflow-hidden hover:shadow-black/50">
            <span className="relative z-10 flex items-center gap-2 font-semibold text-sm tracking-wide">
              <span className="group-hover:animate-pulse">⚡</span>
              Social Corner
              <span className="group-hover:translate-x-1 transition-transform duration-200">→</span>
            </span>
          </Link>
        </div>
      </body>
    </html>
  );
}
